# TCL File Generated by Component Editor 18.1
# Sun Jul 21 14:48:31 JST 2024
# DO NOT MODIFY


# 
# Dynaminc_Phase_Shift_Controler "Dynaminc_Phase_Shift_Controler" v1.0
#  2024.07.21.14:48:31
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Dynaminc_Phase_Shift_Controler
# 
set_module_property DESCRIPTION ""
set_module_property NAME Dynaminc_Phase_Shift_Controler
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP USER_IP
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Dynaminc_Phase_Shift_Controler
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL dyn_phase_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file dyn_phase_reg.v SYSTEM_VERILOG PATH dyn_phase_reg.v
add_fileset_file dyn_phase_stm.v SYSTEM_VERILOG PATH dyn_phase_stm.v
add_fileset_file dyn_phase_top.v SYSTEM_VERILOG PATH dyn_phase_top.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock CLK100M
set_interface_property avalon_slave_0 associatedReset RESET_N
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 AV_CS chipselect Input 1
add_interface_port avalon_slave_0 AV_ADDRESS address Input 13
add_interface_port avalon_slave_0 AV_BEGINTRANSFER begintransfer Input 1
add_interface_port avalon_slave_0 AV_READ read Input 1
add_interface_port avalon_slave_0 AV_WRITE write Input 1
add_interface_port avalon_slave_0 AV_READDATA readdata Output 32
add_interface_port avalon_slave_0 AV_WRITEDATA writedata Input 32
add_interface_port avalon_slave_0 AV_WAITREQUEST waitrequest Output 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point RESET_N
# 
add_interface RESET_N reset end
set_interface_property RESET_N associatedClock CLK100M
set_interface_property RESET_N synchronousEdges DEASSERT
set_interface_property RESET_N ENABLED true
set_interface_property RESET_N EXPORT_OF ""
set_interface_property RESET_N PORT_NAME_MAP ""
set_interface_property RESET_N CMSIS_SVD_VARIABLES ""
set_interface_property RESET_N SVD_ADDRESS_GROUP ""

add_interface_port RESET_N RESET_N reset_n Input 1


# 
# connection point CLK50M
# 
add_interface CLK50M clock end
set_interface_property CLK50M clockRate 50000000
set_interface_property CLK50M ENABLED true
set_interface_property CLK50M EXPORT_OF ""
set_interface_property CLK50M PORT_NAME_MAP ""
set_interface_property CLK50M CMSIS_SVD_VARIABLES ""
set_interface_property CLK50M SVD_ADDRESS_GROUP ""

add_interface_port CLK50M CLK50M clk Input 1


# 
# connection point CLK100M
# 
add_interface CLK100M clock end
set_interface_property CLK100M clockRate 100000000
set_interface_property CLK100M ENABLED true
set_interface_property CLK100M EXPORT_OF ""
set_interface_property CLK100M PORT_NAME_MAP ""
set_interface_property CLK100M CMSIS_SVD_VARIABLES ""
set_interface_property CLK100M SVD_ADDRESS_GROUP ""

add_interface_port CLK100M CLK100M clk Input 1


# 
# connection point PHASEDONE
# 
add_interface PHASEDONE conduit end
set_interface_property PHASEDONE associatedClock CLK50M
set_interface_property PHASEDONE associatedReset RESET_N
set_interface_property PHASEDONE ENABLED true
set_interface_property PHASEDONE EXPORT_OF ""
set_interface_property PHASEDONE PORT_NAME_MAP ""
set_interface_property PHASEDONE CMSIS_SVD_VARIABLES ""
set_interface_property PHASEDONE SVD_ADDRESS_GROUP ""

add_interface_port PHASEDONE PHASEDONE export Input 1


# 
# connection point PHASECOUNTERSELECT
# 
add_interface PHASECOUNTERSELECT conduit end
set_interface_property PHASECOUNTERSELECT associatedClock CLK50M
set_interface_property PHASECOUNTERSELECT associatedReset RESET_N
set_interface_property PHASECOUNTERSELECT ENABLED true
set_interface_property PHASECOUNTERSELECT EXPORT_OF ""
set_interface_property PHASECOUNTERSELECT PORT_NAME_MAP ""
set_interface_property PHASECOUNTERSELECT CMSIS_SVD_VARIABLES ""
set_interface_property PHASECOUNTERSELECT SVD_ADDRESS_GROUP ""

add_interface_port PHASECOUNTERSELECT PHASECOUNTERSELECT readdata Output 4


# 
# connection point PHASEUPDOWN
# 
add_interface PHASEUPDOWN conduit end
set_interface_property PHASEUPDOWN associatedClock CLK50M
set_interface_property PHASEUPDOWN associatedReset RESET_N
set_interface_property PHASEUPDOWN ENABLED true
set_interface_property PHASEUPDOWN EXPORT_OF ""
set_interface_property PHASEUPDOWN PORT_NAME_MAP ""
set_interface_property PHASEUPDOWN CMSIS_SVD_VARIABLES ""
set_interface_property PHASEUPDOWN SVD_ADDRESS_GROUP ""

add_interface_port PHASEUPDOWN PHASEUPDOWN export Output 1


# 
# connection point PHASESTEP
# 
add_interface PHASESTEP conduit end
set_interface_property PHASESTEP associatedClock CLK50M
set_interface_property PHASESTEP associatedReset RESET_N
set_interface_property PHASESTEP ENABLED true
set_interface_property PHASESTEP EXPORT_OF ""
set_interface_property PHASESTEP PORT_NAME_MAP ""
set_interface_property PHASESTEP CMSIS_SVD_VARIABLES ""
set_interface_property PHASESTEP SVD_ADDRESS_GROUP ""

add_interface_port PHASESTEP PHASESTEP export Output 1

